
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// BEREICH
export const CREATE_BEREICH_SUCCESS = "CREATE_BEREICH_SUCCESS";
export const DELETE_BEREICH_SUCCESS = "DELETE_BEREICH_SUCCESS";
export const GET_BEREICH_SUCCESS = "GET_BEREICH_SUCCESS";
export const LIST_BEREICH_SUCCESS = "LIST_BEREICH_SUCCESS";
export const UPDATE_BEREICH_SUCCESS = "UPDATE_BEREICH_SUCCESS";

// TOOL
export const CREATE_TOOL_SUCCESS = "CREATE_TOOL_SUCCESS";
export const DELETE_TOOL_SUCCESS = "DELETE_TOOL_SUCCESS";
export const GET_TOOL_SUCCESS = "GET_TOOL_SUCCESS";
export const LIST_TOOL_SUCCESS = "LIST_TOOL_SUCCESS";
export const UPDATE_TOOL_SUCCESS = "UPDATE_TOOL_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
